require:
  - rubocop-rails

AllCops:
 NewCops: enable
 TargetRubyVersion: 2.6
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**'
   - 'config/**/*'
   - 'spec/rails_helper.rb'
   - 'spec/spec_helper.rb'
   - '**/Gemfile'

Style/Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
 Exclude:
  - 'spec/factories/**/*'

Style/AsciiComments:
  Enabled: false
